spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

usermanagement:
  mongodb:
    replicaset:
      name: rs0
      username: admin
      password: admin
      primary: mongo1
      port: 27017
      database: udemy
      authentication-database: admin
