spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

usermanagement:
  mongodb:
    replicaset:
      name: rs0
      username: admin
      password: admin
      primary: 127.0.0.1
      port: 27019
      database: udemy
      authentication-database: admin
